package com.yourname;

import org.bukkit.Material;

import java.util.EnumSet;
import java.util.Set;

public class BlockGroups {
    public static final Set<Material> SHOVEL_BLOCKS = EnumSet.of(
        Material.DIRT, 
        Material.GRASS_BLOCK, 
        Material.COARSE_DIRT, 
        Material.PODZOL,
        Material.ROOTED_DIRT, 
        Material.SAND, 
        Material.RED_SAND, 
        Material.GRAVEL,
        Material.MYCELIUM, 
        Material.SOUL_SAND, 
        Material.SOUL_SOIL, 
        Material.SNOW_BLOCK,
        Material.SNOW, 
        Material.DIRT_PATH, 
        Material.CLAY, 
        Material.MUD, 
        Material.FARMLAND,
        Material.MUDDY_MANGROVE_ROOTS, 
        Material.SUSPICIOUS_GRAVEL, 
        Material.SUSPICIOUS_SAND
    );

    public static final Set<Material> PICKAXE_BLOCKS = EnumSet.of(
        // Material.AMETHYST_BUD,
        Material.AMETHYST_CLUSTER,
        Material.ANCIENT_DEBRIS,
        Material.ANDESITE,
        // Material.ANVIL,
        Material.BASALT,
        // Material.BELL,
        Material.BLACKSTONE,
        // Material.BLAST_FURNACE,
        Material.BLUE_ICE,
        // Material.BLOCK_OF_AMETHYST,
        // Material.BLOCK_OF_COAL,
        // Material.BLOCK_OF_COPPER,
        // Material.BLOCK_OF_DIAMOND,
        // Material.BLOCK_OF_EMERALD,
        // Material.BLOCK_OF_GOLD,
        // Material.BLOCK_OF_IRON,
        // Material.BLOCK_OF_LAPIS,
        // Material.BLOCK_OF_NETHERITE,
        // Material.BLOCK_OF_QUARTZ,
        // Material.BLOCK_OF_RAW_COPPER,
        // Material.BLOCK_OF_RAW_GOLD,
        // Material.BLOCK_OF_RAW_IRON,
        Material.BONE_BLOCK,
        // Material.BRICKS,
        // Material.BRICK_STAIRS,
        // Material.BREWING_STAND,
        Material.BUDDING_AMETHYST,
        Material.CALCITE,
        // Material.CAULDRON,
        // Material.CHAIN,
        // Material.CHISELED_DEEPSLATE,
        // Material.CHISELED_POLISHED_BLACKSTONE,
        Material.COBBLED_DEEPSLATE,
        Material.COBBLESTONE,
        // Material.COBBLESTONE_STAIRS,
        // Material.COBBLESTONE_WALL,
        Material.COAL_ORE,
        // Material.COMPOUND_CREATOR,
        // Material.CONCRETE,
        // Material.CONDUIT,
        // Material.COPPER_BLOCK,
        Material.COPPER_ORE,
        // Material.CRACKED_STONE_BRICKS, // if used
        Material.CRYING_OBSIDIAN,
        // Material.CUT_COPPER,
        // Material.CUT_COPPER_SLAB,
        // Material.CUT_COPPER_STAIRS,
        Material.DARK_PRISMARINE,
        Material.DEEPSLATE,
        // Material.DEEPSLATE_BRICKS,
        Material.DEEPSLATE_COAL_ORE,
        Material.DEEPSLATE_COPPER_ORE,
        Material.DEEPSLATE_DIAMOND_ORE,
        Material.DEEPSLATE_EMERALD_ORE,
        Material.DEEPSLATE_GOLD_ORE,
        Material.DEEPSLATE_IRON_ORE,
        Material.DEEPSLATE_LAPIS_ORE,
        Material.DEEPSLATE_REDSTONE_ORE,
        Material.DIAMOND_ORE,
        Material.DIORITE,
        // Material.DISPENSER,
        // Material.DRAGON_EGG,
        Material.DRIPSTONE_BLOCK,
        // Material.DROPPER,
        Material.EMERALD_ORE,
        // Material.ENCHANTING_TABLE,
        Material.END_STONE,
        // Material.ENDER_CHEST,
        // Material.FURNACE,
        Material.GILDED_BLACKSTONE,
        // Material.GLASS, // optional if used
        // Material.GLAZED_TERRACOTTA,
        Material.GOLD_ORE,
        Material.GRANITE,
        // Material.GRINDSTONE,
        // Material.HEAT_BLOCK,
        // Material.HOPPER,
        Material.ICE,
        // Material.IRON_BARS,
        // Material.IRON_DOOR,
        Material.IRON_ORE,
        // Material.IRON_TRAPDOOR,
        // Material.LANTERN,
        Material.LAPIS_ORE,
        // Material.LIGHTNING_ROD,
        Material.LODESTONE,
        Material.MAGMA_BLOCK,
        // Material.MONSTER_SPAWNER,
        Material.MOSSY_COBBLESTONE,
        Material.MUD_BRICKS,
        Material.NETHER_BRICK_FENCE,
        Material.NETHER_BRICK_STAIRS,
        Material.NETHER_BRICKS,
        Material.NETHER_GOLD_ORE,
        Material.NETHER_QUARTZ_ORE,
        Material.NETHERRACK,
        // Material.NYLIUM,
        // Material.OBSERVER,
        Material.OBSIDIAN,
        Material.PACKED_ICE,
        Material.PACKED_MUD,
        Material.POINTED_DRIPSTONE,
        Material.POLISHED_BASALT,
        Material.POLISHED_BLACKSTONE,
        Material.POLISHED_BLACKSTONE_BRICKS,
        Material.POLISHED_DEEPSLATE,
        Material.PRISMARINE,
        Material.PRISMARINE_BRICKS,
        Material.PURPUR_BLOCK,
        Material.PURPUR_PILLAR,
        Material.QUARTZ_STAIRS,
        // Material.RAIL,
        Material.RED_NETHER_BRICKS,
        Material.RED_SANDSTONE,
        Material.RED_SANDSTONE_STAIRS,
        Material.REDSTONE_ORE,
        Material.RESPAWN_ANCHOR,
        Material.SANDSTONE,
        Material.SANDSTONE_STAIRS,
        // Material.SHULKER_BOX,
        // Material.SMOKER,
        Material.SMOOTH_BASALT,
        Material.SMOOTH_STONE,
        Material.STONE,
        Material.STONE_BRICK_STAIRS,
        Material.STONE_BRICKS,
        // Material.STONE_BUTTON,
        // Material.STONE_PRESSURE_PLATE,
        Material.STONECUTTER,
        Material.TERRACOTTA,
        Material.TUFF
    );
}